### ISSUE TITLE
Research in the field of VCS

### ISSUE THREAD

**Issue by katunilya** [koomb/art-area#1]
Before actual development, we need to create optimized find out basic information about
-  How `.psd` file is structured
-  How git works (basic git feature of finding file deltas)
-  Is there any way to optimize deltas?
-  How we can store delta data locally?
-  How we can make branching (made in git)?

Useful links were shared but would be duplicated in the thread

All the research results should be posted there, in comments

@mohorka check this out!

**Comment by katunilya** [comment]
### Research Purpose & Goal

We need to find out how we can optimally store data of changes in 2 Photoshop files. We got 2 files - the old one and the new one. We need to find which data was added and which was deleted. Which means that for us it's important to understand the most optimal way of saving data about file change. We can save data changes in some hidden `.txt` inside some hidden folder in the local repository and when a user creates commit program writes in this file info about file differences - new files, changes in old files, deletion and additions. The main point is to make this _delta_ file be lighter than just all the copies of the original file in different time points stored in one place straightly.

**Comment by mohorka** [comment]
Как я вижу один из возможных вариантов решения:
1)построчно сравниваем оба файла с учетом проверок на их корректность (под корректностью я подразумеваю соответствие файлов стандарту)
2)если строки отличаются ,то сохраняем вариант из нового файла в промежуточную структуру данных, для удобства это может быть массив строк, по дефолту заполненный нулями. Индекс ячейки будет соответствовать порядковому номеру строки в исходном файле.
3)с помощью алгоритма переводим непустые ячейки в читабельный вариант и сохраняем их в .txt в следующем виде:
    index description
  где index-порядковый номер измененной строки в исходном файле,
        description-описание свойства строки (например, слой, цвет и т.д.) .
Проблема в том, что промежуточный массив имеет временную сложность O(n),но с другой стороны сложность по памяти O(1);
Если время поиска очень важно, нужно выбирать другую структуру данных.
Также есть проблема с реализацией самого алгоритма перевода из .psd в .txt. Изначально я предполагала использовать ассоциативный массив(map) в
Качестве хранения пар вида "исходные данные из .psd"-"их читабельный вариант для .txt". Но тогда имеем снова временную сложность O(n). 
На хабре нашла возможный вариант решения с использованием хэш-таблиц, но это, насколько я понимаю, затратно по памяти.
Касательно уменьшения размера текстового файла, можно попробовать [сжатие файла](https://habr.com/ru/post/79200/).

**Comment by katunilya** [comment]
@mohorka good result, congrats)

Then I suggest we should do the following:
- [ ] Develop conversion between `.psd` and `.txt` (both directions)
- [ ] Develop the way to find common parts of files and uncommon one - finding delta data
- [ ] Develop delta delta serialization

**Delta Data** - the difference between 2 files which is described as additions and deletions.

Let's decide which language we will use for development. I see 2 options:
- `C++` that we will build as valid CLR library
- Unsafe `C#`

**Additional Context**

I believe we shouldn't spend much time on writing effective and difficult algorithms right now. We should think about its simplicity and robustness.

**Comment by katunilya** [comment]
### Issue Reorganisation

Issue divided into 2 - one for VCS research, another for `.psd` file parsing and analysis support.

This issue is now **only about VCS**, for `.psd` parsing see #4

**Comment by katunilya** [comment]
considered to be overthinking of the problem
