### ISSUE TITLE
Disign MVP Requirements & Project Roadmap

### ISSUE THREAD

**Issue by katunilya** [koomb/art-area#2]
### Problem
Before developing we should design what features we are going to include in our first `0.1` release. 

### Solution
For that, we design a list of features as MVP Requirements. With them, we will design all the issues and tasks for each development step. In this thread, we are going to discuss it and finally write it in the documentation.

First of all, we need to think about what artists really need and how we can provide them the most significant features.

Keep in mind that this is also going to be our development tool

**Comment by katunilya** [comment]
Art Area should be the tool that increases the efficiency of designers and managers (game-designers) interaction. We should provide tools both for designers - Version Control System Tools - and for managers. That's why at first glance it seems reasonable to divide all features into 2 groups - _Design Features_ and _Management Features_

### Design Features

<table>
	<tbody>
		<tr>
			<td><b>Feature Group</b></td>
			<td><b>Feature</b></td>
			<td><b>Intention</b></td>
		</tr>
		<tr>
			<td rowspan="7">Version Control System</td>
			<td>Commits</td>
			<td>Often artist work iterativly - they do work and get edit requests. This becomes a reason for having many different documents in one place for the same project in order to be able to come back to it, if something goes wrong. Commits are hidden so artist can have folder clear and be always ready to turn back.
</td>
		</tr>
		<tr>
			<td>Branching</td>
			<td>In concept art especially artist creates lots of variant for the same object. It can be easier to structurize it not on the level of the file (which becomes large), but on the level of parallel file versions. This can decrease the amount of space that one file needs and allow several designers to work at the same concept or project simultaneously without dividing it into many associated with each other. Branching allows to create branches, but not merge them (as it doesn't seem possible and reasonable to be able to merge images)</td>
		</tr>
		<tr>
			<td>Stashing </td>
			<td> Sometimes we need to switch branches, but we have uncommitted changes. So we can stash deltas - make local unseen "commit" that we can come back afterword. For our project, we will stash changes automatically when the designer switches branches so that he won't accidentally lose everything because of VCS</td>
		</tr>
		<tr>
			<td>Commit Jumps</td>
			<td> Core commits feature that allows the designer to choose the new branch from any commit without actual revert (we do not undo commits we've done, but say we want to try another way of doing things since this commit)</td>
		</tr>
		<tr>
			<td>Software Integration</td>
			<td>We don't want users to close/open their software every time they want to commit something, for that we could create extensions for their software that will do it from their editor.</td>
        	</tr>
		<tr>
			<td>Auto Commits for Software Extensions</td>
			<td>We can add auto commits feature for software intergrations (extensions) that will generate a new commit everytime designer uses special hotkey</td>
		</tr>
		<tr>
			<td>(*)Commit Merges</td>
			<td>Designer should be able to merge commits (skip step if it's not needed). </td>
		</tr>
	</tbody>
</table>

**Comment by mohorka** [comment]
Для начала, мне кажется, стоит остановится на версии только для дизайнеров. Я не очень понимаю,что можно добавить в art-area для менеджеров, разве что issues, которые могут использовать и дизайнеры для обсуждения деталей работы над проектом. Но это явно не основное, к тому же пока мы работаем только над локальным репозиторием. Для первой версии,думаю, будет достаточно возможности коммитить, создавать несколько ветвей и интеграции с software. Еще можно расширить пункт auto commits-сделать возможным автокоммит через определенный интервал времени,например, каждый час или раз в день при наличии каких-либо изменений в проекте.

**Comment by katunilya** [comment]
@mohorka I see some points I disagree with.

1. MVP is the full core features and mechanism list. It shouldn't be too restricted. 

1. I want to make an accent that **Art Area is the application that should automate pipeline for visual development** (design documents, review and edit requests)

1. MVP is not about first working version, but about release candidate (I would say so) requirements

1. That's why we need to build up features that will cover the entire pipeline which usually looks like this:
   - The design document is written and sent to the artist (disdoc consists of a description and sometimes references for the art)
   - Artist creates different versions for what was requested (there branching and committing can help much)
   - Ideas are reviewed and there starts an iterative process of reviewing and  editing drawing more and  more
   - Final art can be sent as a reference to some other artists like 3D modelers who have generally the same problems and pipeline

   That's why we need to see the whole picture and find core features that will build up our application. This will provide us the opportunity to add other features upon them that won't break the UX.

1. I believe that integration to original software is not a core feature (if we do it then we won't need a desktop client which is the first step)

1. Auto-commits are considered (good idea 👍), but still seems to be an addition upon commit feature

1. ⚠️ I suggest keeping the list of approved features for MVP in the header message for the thread and discuss more in comments for it. Or we can make a gist and discuss it in comments for that - wait for your feedback on this @mohorka 

1. Please give a concrete list of features that you approve (from [this](https://github.com/amcp-team/art-area/issues/2#issuecomment-513465546) message) and suggest yours if you have them of course

**Comment by mohorka** [comment]
Я подумала,но ничего нового добавить не могу, ты и так все самое нужное указал в списке. Единственно, я бы убрала merge все-таки,мне кажется это лишнее

**Comment by hypnospinner** [comment]
### Management Features Suggestion

As the purpose of our project is **full automation of visual development** I find it crucial to think about management features in advance and suggest the following:

<table>
	<tbody>
		<tr>
			<td><b>Feature</b></td>
			<td><b>Intention</b></td>
		</tr>
		<tr>
			<td>Repository Structure</td>
			<td>Repository is just a folder which stores files associated with one huge project. All finished drawings or renders are going to be shown in the section called <i>Gallery</i> (same as <i>Code</i> in GitHub). Each distinct piece of work (for example all art created for some character - concepts, references, renders, final model, textures, etc.) will be called <i>Canvas</i> (successor of <i>Projects</i> tab). Each Canvas has distinct slideshow card in Gallery tab, provided with design documentation and canban boards. <i>Review Board</i>is a special section where designers or managers can review one's work and leave comments on it and than integrate it to <i>master</i> branch. <i>Tickets</i> is a tab for tasks which can be bound to some <i>Canvas</i>, generally it's suggested to create only one ticket for one <i>Canvas</i>, but it can be possible to create more. Also <i>Ticket</i> can be marked as <i>head</i>, which will make it a design document for concrete <i>Canvas</i>.<td>
		</tr>
		<tr>
			<td>Tickets</td>
			<td>Usually artist gets designer documentation that has a full description of what artist is supposed to draw. I believe that should be implemented like issues on GitHub with a couple of changes. Following are supposed requirements:
				<ul>
					<li>Ticket uses markdown</li>
					<li>Ticket can be assigned to some designers (0+)</li>
					<li>Ticket can be marked with some labels</li>
					<li>Ticket can be bound to some deadline</li>
					<li></li>
					<li></li>
					<li></li>
					<li></li>
					<li></li>
				</ul>
			</td>
                 </tr>
		<tr>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td></td>
			<td></td>
		</tr>
	</tbody>
</table>

**Comment by katunilya** [comment]
### Management Functionality

Firstly we suppose that an artist is not going to store anything except `.psd` files in folders, because all text files and reference images will be accepted by him through our service. All files should be structured:
- Files that are associated with some subproject (for example visuals for the main hero of the game - concept art, models, renders, textures, etc.) should be grouped inside **Canvas**
- Files that are not associated are stored in default **Stash Canvas**

**Gallery** is the main page of the repository - their user sees all the public Canvases as cards with some title and image (or several switching images). Images that are displayed on the Canvas are _Master Thumbnails_ - some final renders or versions that were marked for displaying. Canvas can be opened - which means that the design & art is not done yet and closed which means that this artwork is finished.

Canvas is a structure which reminds of a folder with some thread. In this thread, one can send different types of messages:
- **Design Document** - many messages per thread, text file in markdown that describes what should be drawn (with reference images)
- **Review Request** - many per thread, an image with the link to the source file
- **Review (Edit Request, Approve or Comment)** - many per thread, one-to-one with Review Request messages, the message that extends Review Request - manager opens special Review section where one can highlight different parts of the image attached and comment them, requesting some changes or approving
- **Comment** - many per thread, discussion for manages and artist

Canvas design document message can be labeled, bound with some deadline, assigned to some collaborators.

> * The design document is written and sent to the artist (disdoc consists of a description and sometimes references for the art)
> * Artist creates different versions for what was requested (there branching and committing can help much)
> * Ideas are reviewed and there starts an iterative process of reviewing and  editing drawing more and  more
> * Final art can be sent as a reference to some other artists like 3D modelers who have generally the same problems and pipeline

This approach fully covers the general art creation process:

1. The manager or some other designer creates a Canvas and writes Design Document, attaches some references, assigns artists, deadlines, etc.
1. Artist creates some files and bounds them to the Canvas and starts development
1. When artists finished one suggests his art (choosing file & branch with sent for review file version) with Review Request message in Canvas thread
1. The file is reviewed and there starts an iteration of redrawing
1. When work is finished new design document can be written and some other artist (for example 3D artist) based on done work creates his part of materials needed for this artwork

---

### Desktop Client Functinality

It should allow a user to 
- Send files to the remote repository
- Create branches for files and commit them 
- Send commits to the remote repo and receive commits
- Switch between canvases & choose what canvases to store locally
- Add files to canvases
- Create review requests

@mohorka waiting for your review and suggestions

**Comment by katunilya** [comment]
### UPD for [pervious comment](https://github.com/koomb/art-area/issues/2#issuecomment-516288113)

Attach a rough mockup for repository page
![Repository Page](https://user-images.githubusercontent.com/40162026/62143407-9dc3d000-b2f8-11e9-82f0-2a9210666794.jpg)

**Comment by katunilya** [comment]
This issue is closed, will be reopen closer to FLS Hackathon (end of October 2019)
