### ISSUE TITLE
Страница: Project Page + Controller

### ISSUE THREAD

**Issue by katunilya** [koomb/art-area#20]
### Problem caused feature request
Страница проекта предоставляет основную функциональность по работе с проектами: создание новых досок, добавление новых участников, тэгов, навигация к Review Request'ам, переход к существующим доскам

### Requested Solution 
Страница должна отображать данные по проекту - его название, краткое описание (если есть), список всех досок и кнопку по добавлению новых элементов проекта - пока только досок.
- [x] fetch запрос на данные проекта
- [x] fetch запрос на доски (исходя из данных залогиненного юзера)
    Для пользователю (или отсутствию залогиненного пользователя) мы проверяем какие данные он имеет право просматривать (доски) их мы и вернем как результат этого запроса

**Route** : `../{username}/{project-name}` ❓ Здесь нужно подумать, как удобнее - будем ли мы строго привязывать проект к пользователю (админу) или нет?
**Контроллер** : `ProjectController`
**Ветка для фронта** : `feature/project-page-front`
**Ветка для бэка** : `feature/project-page-api`
**Ветка для интеграции** : `feature/project-page-integration`

Blocked #19

**Comment by SixDevelop** [comment]
нужны данные формата project(title,id,author,description) по эндпоинту 'api/user/:username/title' + title'

**Comment by katunilya** [comment]
@SixDevelop т.к. при переходе на страницу проекта ты уже знаешь его id, то было бы лучше, если бы ты кинул на бэк запрос
```
.../api/project/{project_id}
```

Мы вернем тебе данные в формате
```json
{
	"title": "project-title-here",
	"id": "project-id-here",
	"author": "project-creator-there",
	"description": "project-description-there"
}
```

---

Думаю нам так же понадобится эндпоинты для 
- всех досок внутри проекта
- всех участников проекта

Ну это как самые важные 

@mohorka check dat out
