### ISSUE TITLE
Страница: Board Page + Controller

### ISSUE THREAD

**Issue by katunilya** [koomb/art-area#21]
### Problem caused feature request
На странице доски мы отображаем задачу, исходные файлы и ассоциированные с ними пины (коммиты) с превьюшками

### Requested Solution 
На этой странице нужно грузить много изображений и она самая сложная из всех (примерно). Страница принимает id доски в рамках проекта (т.е. переходя на страницу мы будем отправлять данные по проекту и id (номеру) доски в рамках проекта.
⚠️ Нужен реально _очень хороший и функциональный_ дизайн для этой страницы, который по большей части и повлияет на требуемый ей интерфейс взаимодействия с сервером
- [x] fetch для получения данных о доске (название, описание)
- [ ] fetch для загрузки задачи (некоторого текстового фрагмента, пока что неформатированного)
- [ ] fetch для загрузки коротких данных об исходниках
- [ ] fetch для загрузки списка пинов для конкретного исходника

**Route** : `../{username}/{projectname}/{boardId = int}`
**Контроллер** : `BoardController`
**Ветка для фронта** : `feature/board-page-front`
**Ветка для бэка** : `feature/board-page-api`
**Ветка для интеграции** `feature/board-page-integration`

Blocked #19 #20

**Comment by SixDevelop** [comment]
мне нужно получить модель 
 title: string;
  id: string;
  description: string;
  boardNumber: string;
 по эндпоинту "api/board/data/"
ещё мне нужны 
export class Pin {
  title: string;
  id: string;
  description: string;
}
по эндпоинту "api/board/pins/" @mohorka

**Comment by katunilya** [comment]
@SixDevelop учите доменную область

У Pin нет description и title, есть объект Message, который нужно представить как подпись к данному пину, поэтому вы получите:

```typescript
message 
{
	id:string,
	message:{
		id:string,
		text:string,
		date:Date,
		author:string
}
```

соответственно аналогичную структуру должны вернуть и мы по запросу @mohorka 

P.S. учите маркдаун, что нормально оформлять сообщения - хотя бы помещать код в тройные или одинарные апострофы: 
``` 
`put code in here`
```
