### ISSUE TITLE
Страница: Pin Page + Controller

### ISSUE THREAD

**Issue by katunilya** [koomb/art-area#22]
### Problem caused feature request
Нам нужно отображать данные о конкретном пине, конкретной точке в истории конкретного прикрепленного исходного файла. Пин должен отображать ленту комментариев (и позволят добавлять новые к нему), отображать изображение-заглушки (thumbnail), а так же позволять скачивать исходник прикрепленный к пину (если он есть)

### Requested Solution 
Опять же нужно учитывать, что не каждый юзер имеет доступ к любому пину и доске, так что если кто-то хочет через url напрямую получит доступ к скрытым данным, мы должны выдать ему ошибку поиска (404)
- [ ] ⚠️ Дизайн для страницы пина
- [ ] fetch на короткие данные по пину (название и заголовочное сообщение)
- [ ] fetch на изображение заглушку
- [ ] fetch на загрузку исходника
- [ ] fetch на загрузку комментариев
- [ ] fetch на отправку нового комментария

**Route** : `../{username}/{project-name}/{boardId = int}/pin/{pinId - stringed ObjectId}` ❓ Возможно мы можем как-то укоротить длину URL
**Контроллер** : `PinController`
**Ветка для фронта** : `feature/pin-page-front`
**Ветка для бэка** : `feature/pin-page-api`
**Ветка для интеграции** : `feature/pin-page-integration`

Blocked #19 #20 #21

**Comment by SixDevelop** [comment]
нужны данные типа
```
export class Message {
	id:string;
	message:{
		id:string,
		text:string,
		date:Date,
		author:string
  }
}
```

по эндпоинту `"api/messages/data/"`

**Comment by katunilya** [comment]
@SixDevelop мне кажется лучше грузить все сообщения разом а не по одному, поэтому я предлагаю сделать следующее

Мы пока отображаем плейсхолдер изображения вместо реального и просто отображаем список сообщений (т.е. возвращаем некоторый массив сообщений). Все это по эндпоинту 

`api/pin/messages/{id}` где `{id}` - ИД пина
