### ISSUE TITLE
Страницы создания

### ISSUE THREAD

**Issue by katunilya** [koomb/art-area#23]
### Problem caused feature request
Нам нужен ряд страниц с которых пользователь может создавать новые объекты в нашей системе - проекты, доски, пины и т.д.

### Requested Solution 
Нужно три страницы с простыми формами и fetch-запросами который будут в случае успеха редиректить на только что созданный объект (т.е. на страницу пина, доски или проекта)
- [x] Create Project Page
- [x] Create Board Page
- [x] Create Pin Page

В идеале на них должна асинхронно проводиться валидация данных

**Route** : 
    `../{username}/create`
    `../{username}/{projectname}/create`
    `../{username}/{projectname}/{boardId}/create`
**Контроллеры** : `ProjectController`, `BoardController`, `PinController`
**Ветка для фронта** : `feature/creation-pages-front`
**Ветка для бэка** : `feature/creation-pages-api`
**Интеграция** : `feature/creation-pages-integration`

Blocked #19 #20 #21 #22

**Comment by SixDevelop** [comment]
@hypnospinner please check creating project

**Comment by SixDevelop** [comment]
мне нужны title, description по эндпоинтам "api/project/create"; "api/board/create"
это для создания проекта и доски @mohorka
