### ISSUE TITLE
Слой данных: MongoDB

### ISSUE THREAD

**Issue by katunilya** [koomb/art-area#27]
### Problem caused feature request
Теперь нам нужно разработать реальные репозитории для работы с данными в MongoDb (MongoDb.Driver + GridFS)

### Requested Solution 
Аналогичным образом #26 на основе уже созданных интерфейсов разрабатываются реальные методы доступа к данным посредством MongoDb (через класс контекста данных)

Нужно реализовать репозитории для:
   - [x] Проекты
   - [x] Доски
   - [x] Пользователи
   - [ ] Пины исходников (Pin Group)
   - [x] Пины

**Ветка** : `feature/data-layer-mongo`

Blocked #26

**Comment by AndyS1mpson** [comment]
Pin group мы решили убрать
Остальное сделано
